### ISSUE TITLE
Can i use this in my Legion 5-15IMH05?

### ISSUE THREAD

**Issue by Revindran** [yusufklncc/Lenovo-Legion-5-Hackintosh#12]
Hi thanks for sharing this efi
I would like to install this in my Legion 5-15IMH05,
can it work?

**Comment by yusufklncc** [comment]
Try

**Comment by f3sa** [comment]
### **To make this EFI work with Intel Wi-Fi and Bluetooth, you gotta follow a couple steps.**

For this guide you will need a USB flash drive to copy certain kext files from Windows to Mac.

1. Download the EFI of this current repository and extract it to your Windows desktop.
2. Open the config.plist and remove code from line 941-958. (the `<dict></dict>` block)
3. Download AirportBrcmFixup-2.1.7-RELEASE.zip from [here](https://github.com/acidanthera/AirportBrcmFixup/releases).
4. Extract AirportBrcmFixup.kext and copy it to EFI/OC/Kexts.
5. Open EFI/OC/config.plist and add the following code from line 509: ` <dict>
                    <key>Arch</key>
                    <string>Any</string>
                    <key>BundlePath</key>
                    <string>AirportBrcmFixup.kext</string>
                    <key>Comment</key>
                    <string></string>
                    <key>Enabled</key>
                    <true/>
                    <key>ExecutablePath</key>
                    <string>Contents/MacOS/AirportBrcmFixup</string>
                    <key>MaxKernel</key>
                    <string></string>
                    <key>MinKernel</key>
                    <string></string>
                    <key>PlistPath</key>
                    <string>Contents/Info.plist</string>
			    </dict>` 
7. Next you wanna upload the EFI folder to your macOS EFI drive with e.g. Explorer++.
8. Download AirportItlwm-Ventura-v2.2.0-DEBUG-alpha-ddd2768.zip from [here](https://github.com/OpenIntelWireless/itlwm/releases).
9. Extract the AirportItlwm.kext from the ZIP file and just copy them on your USB.
10. Download IntelBluetooth-v2.2.0.zip from here[](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases).
11. Extract only IntelBTPatcher.kext and IntelBluetoothFirmware.kext and also copy them onto your USB.
12. Download BrcmPatchRAM-2.6.5-RELEASE.zip from [here](https://github.com/acidanthera/BrcmPatchRAM/releases/tag/2.6.5).
13. Only extract BlueToolFixup.kext and copy it over to your USB.

That's part 1, now make sure you have the following files in your USB flash drive before continuing.
- AirportItlwm.kext
- IntelBTPatcher.kext
- IntelBluetoothFirmware.kext
- BlueToolFixup.kext

Now eject the USB from your Windows system and reboot into Hackintosh with the modified EFI (The one you modifed the config.plist of earlier + make sure you uploaded this modified EFI in your EFI drive with e.g. Explorer++).

14. Boot into macOS Ventura Hackintosh
15. start up OCC (OpenCore Configurator). (If you don't have this on your mac because you can't download it, download it in Windows & put it on your USB).
16. Mount your macOS drive with ESP Mounter Pro and open the drive's Volume.
17. Go to ./OC/ and right-click on config.plist and select "Open With OpenCore Configurator".
18. Go to the Kernel tab and now remove the AirportBrcmFixup.kext (We only needed this to be able to boot correctly).
19. Now plug-in your USB and extract those Kexts over to your Desktop.
20. You can now drag-and-drop those Kexts files over to the Kernel list in OCC (IMPORTANT: Delete them from your kernel list first if they are listed).
21. Order them in such a way that they all come after the AppleALC.kext.
22. now add those Kexts files in your EFI/OC/Kexts/ folder as well.

What you did just now was you edited your config.plist to recognize the newly added Kexts files and now will work with them. Make sure you click top left and click on "Save".

Reboot your Hackintosh and Wi-Fi and Bluetooth should now be working perfect.

**Comment by yusufklncc** [comment]
Thanks but what exactly AirportBrcm kext do?

**Comment by f3sa** [comment]
Without AirportBrcm, the Wi-Fi option becomes disabled.

**Comment by yashj1212** [comment]
> Hi thanks for sharing this efi I would like to install this in my Legion 5-15IMH05, can it work?

What is your exact wifi card?
